# Generated by Django 4.2.24 on 2025-10-22 21:49

from django.db import migrations


class Migration(migrations.Migration):
    """
    Initial migration that ensures casbin_adapter migrations are run.

    This migration creates a dependency on casbin_adapter's initial migration,
    ensuring that when you run 'migrate openedx_authz', the CasbinRule table
    is created automatically by the casbin_adapter app.
    """

    initial = True

    dependencies = [
        # Depend on casbin_adapter's initial migration to ensure
        # the CasbinRule table is created when migrating openedx_authz
        ("casbin_adapter", "0001_initial"),
    ]

    # No operations needed in this migration as we're only
    # establishing the dependency on casbin_adapter
    operations = []
