# Generated by Django 4.2.24 on 2025-10-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("casbin_adapter", "0001_initial"),
        ("openedx_authz", "0001_add_casbin_dependency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExtendedCasbinRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("casbin_rule_key", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "casbin_rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extended_rule",
                        to="casbin_adapter.casbinrule",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casbin_rules",
                        to="openedx_authz.scope",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casbin_rules",
                        to="openedx_authz.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extended Casbin Rule",
                "verbose_name_plural": "Extended Casbin Rules",
            },
        ),
    ]
