# Generated by Django 4.2.24 on 2025-10-24 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openedx_authz", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubject",
            fields=[
                (
                    "subject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="openedx_authz.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authz_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("openedx_authz.subject",),
        ),
    ]
