# Generated by Django 4.2.24 on 2025-10-24 11:19
# Custom migration - DO NOT REGENERATE
# This migration conditionally depends on the content library model based on settings

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openedx_authz", "0003_usersubject"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentLibraryScope",
            fields=[
                (
                    "scope_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="openedx_authz.scope",
                    ),
                ),
                (
                    "content_library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authz_scopes",
                        to=settings.OPENEDX_AUTHZ_CONTENT_LIBRARY_MODEL,
                    ),
                ),
            ],
            bases=("openedx_authz.scope",),
        ),
    ]
