# Generated by Django 4.2.24 on 2025-11-14 22:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openedx_authz", "0004_contentlibraryscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyCacheControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
