"""
Constants for library roles and permissions tests.
"""

from openedx_authz.api.data import ActionData, PermissionData

LIST_LIBRARY_ADMIN_PERMISSIONS = [
    PermissionData(
        action=ActionData(external_key="view_library"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="manage_library_tags"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="delete_library"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="edit_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="publish_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="reuse_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="view_library_team"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="manage_library_team"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="create_library_collection"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="edit_library_collection"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="delete_library_collection"),
        effect="allow",
    ),
]

LIST_LIBRARY_AUTHOR_PERMISSIONS = [
    PermissionData(
        action=ActionData(external_key="view_library"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="manage_library_tags"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="edit_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="publish_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="reuse_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="view_library_team"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="create_library_collection"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="edit_library_collection"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="delete_library_collection"),
        effect="allow",
    ),
]

LIST_LIBRARY_CONTRIBUTOR_PERMISSIONS = [
    PermissionData(
        action=ActionData(external_key="view_library"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="manage_library_tags"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="edit_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="reuse_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="view_library_team"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="create_library_collection"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="edit_library_collection"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="delete_library_collection"),
        effect="allow",
    ),
]

LIST_LIBRARY_USER_PERMISSIONS = [
    PermissionData(
        action=ActionData(external_key="view_library"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="reuse_library_content"),
        effect="allow",
    ),
    PermissionData(
        action=ActionData(external_key="view_library_team"),
        effect="allow",
    ),
]
